// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv5IGH-khSB5tkRyCaXuyp3KyTGWmfMXQ',
    appId: '1:215054783977:web:4e217d0719a329dd4b2778',
    messagingSenderId: '215054783977',
    projectId: 'market-watcher-14891',
    authDomain: 'market-watcher-14891.firebaseapp.com',
    storageBucket: 'market-watcher-14891.firebasestorage.app',
    measurementId: 'G-XLSDXQCVD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLw2X5KRarlpQHVdl5D-Tmryyl4DgU1Fg',
    appId: '1:215054783977:android:312fb280a1692feb4b2778',
    messagingSenderId: '215054783977',
    projectId: 'market-watcher-14891',
    storageBucket: 'market-watcher-14891.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD11Qnd4NQ6f30m0VpcgNodsd8kKTznIP4',
    appId: '1:215054783977:ios:f7f42a2169311e434b2778',
    messagingSenderId: '215054783977',
    projectId: 'market-watcher-14891',
    storageBucket: 'market-watcher-14891.firebasestorage.app',
    iosBundleId: 'com.example.marketWatcherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD11Qnd4NQ6f30m0VpcgNodsd8kKTznIP4',
    appId: '1:215054783977:ios:f7f42a2169311e434b2778',
    messagingSenderId: '215054783977',
    projectId: 'market-watcher-14891',
    storageBucket: 'market-watcher-14891.firebasestorage.app',
    iosBundleId: 'com.example.marketWatcherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv5IGH-khSB5tkRyCaXuyp3KyTGWmfMXQ',
    appId: '1:215054783977:web:8598168dc06e42da4b2778',
    messagingSenderId: '215054783977',
    projectId: 'market-watcher-14891',
    authDomain: 'market-watcher-14891.firebaseapp.com',
    storageBucket: 'market-watcher-14891.firebasestorage.app',
    measurementId: 'G-8LJLLMTY91',
  );

}