name: market_watcher_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.8
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.1.0
  http: ^1.1.0
  flutter_slidable: ^3.1.0
  flutter_screenutil: ^5.9.3
  provider: ^6.1.5+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/